### ISSUE TITLE
try again here

### ISSUE THREAD

**Issue by fgregg** [fgregg/datasette#1]
hi @yejiyang, you should try to use this repo again now.

**Comment by yejiyang** [comment]
@fgregg Thanks for helping out. I tested your branch `no_limit_csv_publish` and it works great now 🚀🚀🚀. 
I am curious what's your plan for the future of this branch. I realized you routed it back to 1.0a1. Do you plan to sync it with the latest datasette main branch? I think your approach here - full data rows in csv & limit rows in table is a great idea. To push back to the upstream would be the best scenario in my opintion.

**Comment by fgregg** [comment]
i may, but have no plans. simon is choosy about what he brings in.

**Comment by yejiyang** [comment]
@fgregg Hey, I saw you updated this branch `no_limit_csv_publish`. Does it work on your side?

**Comment by fgregg** [comment]
yep!

**Comment by yejiyang** [comment]
@fgregg Hei, I tried you branch `no_limit_csv_publish` again, with the templates from [here ](https://github.com/labordata/warehouse/tree/main/templates). I got this error. Do you know if I should also update the templates somewhere?
```
2023-12-11 12:29:09 INFO:     172.23.0.1:57784 - "GET /-/static/sql-formatter-2.3.3.min.js HTTP/1.1" 200 OK
2023-12-11 12:29:14 Traceback (most recent call last):
2023-12-11 12:29:14   File "/usr/local/lib/python3.9/site-packages/datasette/app.py", line 1632, in route_path
2023-12-11 12:29:14     response = await view(request, send)
2023-12-11 12:29:14   File "/usr/local/lib/python3.9/site-packages/datasette/app.py", line 1814, in async_view_fn
2023-12-11 12:29:14     response = await async_call_with_supported_arguments(
2023-12-11 12:29:14   File "/usr/local/lib/python3.9/site-packages/datasette/utils/__init__.py", line 1016, in async_call_with_supported_arguments
2023-12-11 12:29:14     return await fn(*call_with)
2023-12-11 12:29:14   File "/usr/local/lib/python3.9/site-packages/datasette/views/table.py", line 673, in table_view
2023-12-11 12:29:14     response = await table_view_traced(datasette, request)
2023-12-11 12:29:14   File "/usr/local/lib/python3.9/site-packages/datasette/views/table.py", line 822, in table_view_traced
2023-12-11 12:29:14     await datasette.render_template(
2023-12-11 12:29:14   File "/usr/local/lib/python3.9/site-packages/datasette/app.py", line 1307, in render_template
2023-12-11 12:29:14     return await template.render_async(template_context)
2023-12-11 12:29:14   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1324, in render_async
2023-12-11 12:29:14     return self.environment.handle_exception()
2023-12-11 12:29:14   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
2023-12-11 12:29:14     raise rewrite_traceback_stack(source=source)
2023-12-11 12:29:14   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1321, in <listcomp>
2023-12-11 12:29:14     [n async for n in self.root_render_func(ctx)]  # type: ignore
2023-12-11 12:29:14   File "/mnt/templates/table.html", line 1, in top-level template code
2023-12-11 12:29:14     {% extends "base.html" %}
2023-12-11 12:29:14   File "/usr/local/lib/python3.9/site-packages/datasette/templates/base.html", line 62, in top-level template code
2023-12-11 12:29:14     {% block content %}
2023-12-11 12:29:14   File "/mnt/templates/table.html", line 24, in block 'content'
2023-12-11 12:29:14     <div class="page-header" style="border-color: #{{ database_color(database) }}">
2023-12-11 12:29:14 TypeError: 'str' object is not callable
2023-12-11 12:29:14 INFO:     172.23.0.1:57822 - "GET /zeropm-v0-0-3/api_services HTTP/1.1" 500 Internal Server Error
```

**Comment by fgregg** [comment]
it’s working for me. did you manually set the database color anywhere?

**Comment by yejiyang** [comment]
> It’s working for me. did you manually set the database color anywhere? 


Thanks for the quick reply. No color change. I used a `metadata.yml` file, which looks like [this](https://github.com/ZeroPM-H2020/global-chemical-inventory-database/blob/prototype/max_returned_rows-with-templates/metadata.yml).

**Comment by fgregg** [comment]
Closing — leftover onboarding/test issue, not tracking any work.
